CREATE TABLE `sap_maintenance_plan_header_data`
(
  `MaintenancePlan`                   varchar(12) NOT NULL,
  `MaintenancePlanDesc`               varchar(40) DEFAULT NULL,
  `CreationDate`                      varchar(80) DEFAULT NULL,
  `LastChangeDate`                    varchar(80) DEFAULT NULL,
  `MaintenanceStrategy`               varchar(6) DEFAULT NULL,
  `SchedulingDuration`                varchar(3) DEFAULT NULL,
  `SchedulingDurationUnit`            varchar(3) DEFAULT NULL,
  `NumberOfMaintenanceItems`          varchar(4) DEFAULT NULL,
  `CycleModificationRatio`            varchar(5) DEFAULT NULL,
  `MaintPlanSchedgIndicator`          varchar(1) DEFAULT NULL,
  `MaintenancePlanInternalID`         varchar(22) DEFAULT NULL,
  `MaintenanceCall`                   int(32) DEFAULT NULL,
  `MaintenancePlanCategory`           varchar(2) DEFAULT NULL,
  `MaintPlanFreeDefinedAttrib`        varchar(20) DEFAULT NULL,
  `BasicStartDate`                    varchar(80) DEFAULT NULL,
  `SchedulingStartDate`               varchar(80) DEFAULT NULL,
  `SchedulingStartTime`               varchar(80) DEFAULT NULL,
  `MaintPlanStartCntrReadingValue`    varchar(22) DEFAULT NULL,
  `MaintPlnStrtBufDurationInDays`     varchar(3) DEFAULT NULL,
  `MaintPlanStartBufferUnit`          varchar(3) DEFAULT NULL,
  `FactoryCalendar`                   varchar(2) DEFAULT NULL,
  `LateCompletionShiftInPercent`      varchar(3) DEFAULT NULL,
  `LateCompletionTolerancePercent`    varchar(3) DEFAULT NULL,
  `EarlyCompletionShiftInPercent`     varchar(3) DEFAULT NULL,
  `EarlyCompletionTolerancePct`       varchar(3) DEFAULT NULL,
  `MaintPlanLogicalOperatorCode`      varchar(1) DEFAULT NULL,
  `SchedulingEndDate`                 varchar(80) DEFAULT NULL,
  `MaintPlanEndCntrReadingValue`      varchar(22) DEFAULT NULL,
  `LastChangeDateTime`                varchar(80) DEFAULT NULL,
  `MultipleCounterPlanShiftFactor`    varchar(1) DEFAULT NULL,
  `MaintenanceLeadFloatInDays`        varchar(3) DEFAULT NULL,
  `MaintenancePlanCallObject`         varchar(1) DEFAULT NULL,
  `MaintenancePlanSystemStatus`       varchar(30) DEFAULT NULL,
    PRIMARY KEY (`MaintenancePlan`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
